import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'
import Providers from '@/providers/Providers'

const rubik = Rubik({
    weight: ['300', '400', '500', '700'],
    style: 'normal',
    subsets: ['latin'],
})
export const metadata: Metadata = {
    title: 'DOiT MVP',
    description: 'Generated by create next app',
}

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) => {
    return (
        <html lang='en'>
            <body className={`${rubik.className} antialiased`}>
                <Providers>
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    )
}

export default RootLayout
